POST https://api-deslocamento.herokuapp.com/api/v1/Cliente
Content-Type: application/json

{
    "id": 153,
    "numeroDocumento": "123456789",
    "tipoDocumento": "RG",
    "nome": "Test 1",
    "logradouro": "Rua de Teste",
    "numero": "2213",
    "bairro": "Centro",    
    "cidade": "Curitiba",
    "uf": "SP"
}

###
GET https://api-deslocamento.herokuapp.com/api/v1/Cliente

###
DELETE https://api-deslocamento.herokuapp.com/api/v1/Cliente/137
Content-Type: application/json

{
  "id": 137
}

###
PUT https://api-deslocamento.herokuapp.com/api/v1/Cliente/165
Content-Type: application/json

{
 "id": 165,
  "nome": "Teste 2",
  "logradouro": "editado",
  "numero": "djfjsh dsd",
  "bairro": "kmdkja ijfa",
  "cidade": "oz",
  "uf": "sp"
}

# Condutor

###
GET https://api-deslocamento.herokuapp.com/api/v1/Condutor

###
POST https://api-deslocamento.herokuapp.com/api/v1/Condutor
Content-Type: application/json

{
  "nome": "Teste 2",
  "numeroHabilitacao": "3232332",
  "categoriaHabilitacao": "A",
  "vencimentoHabilitacao": "2023-10-20T13:39:40.335Z"
}

###
DELETE  https://api-deslocamento.herokuapp.com/api/v1/Condutor/158
Content-Type: application/json

{
  "id":158
}

# Veiculos

###
GET https://api-deslocamento.herokuapp.com/api/v1/Veiculo

###
POST https://api-deslocamento.herokuapp.com/api/v1/Veiculo
Content-Type: application/json

{
  "placa": "QSQ-2221",
  "marcaModelo": "Palio",
  "anoFabricacao": 2000,
  "kmAtual": 0
}

# Deslocamento
###
GET https://api-deslocamento.herokuapp.com/api/v1/Deslocamento/13



###
POST https://api-deslocamento.herokuapp.com/api/v1/Deslocamento/IniciarDeslocamento
Content-Type: application/json

{
  "kmInicial": 3,
  "inicioDeslocamento": "2023-06-22T00:19:30.857Z",
  "checkList": "Lista de trabalho",
  "motivo": "Saida para o trabalho",
  "observacao": "Inico de deslocamento de Teste",
  "idCondutor": 42,
  "idVeiculo": 24,
  "idCliente": 43
}

###
PUT https://api-deslocamento.herokuapp.com/api/v1/Deslocamento/12/EncerrarDeslocamento
Content-Type: application/json

{
  "id": 12,
  "kmFinal": 330,
  "fimDeslocamento": "2023-06-24T02:56:07.493Z",
  "observacao": "Fim do deslocamento"
}