POST https://api-deslocamento.herokuapp.com/api/v1/Cliente
Content-Type: application/json

{
    "id": 153,
    "numeroDocumento": "123456789",
    "tipoDocumento": "RG",
    "nome": "Test 1",
    "logradouro": "Rua de Teste",
    "numero": "2213",
    "bairro": "Centro",    
    "cidade": "Curitiba",
    "uf": "SP"
}

###
GET https://api-deslocamento.herokuapp.com/api/v1/Cliente/83

###
DELETE https://api-deslocamento.herokuapp.com/api/v1/Cliente/29
Content-Type: application/json

{
  "id": 29
}

###
PUT https://api-deslocamento.herokuapp.com/api/v1/Cliente/31
Content-Type: application/json

{
  "id": 31,
  "nome": "Meu Ovo",
  "logradouro": "Teste",
  "numero": "Teste 3",
  "bairro": "wqeq",
  "cidade": "string",
  "uf": "string"
}

# Condutor

###
GET https://api-deslocamento.herokuapp.com/api/v1/Condutor

###
POST https://api-deslocamento.herokuapp.com/api/v1/Condutor
Content-Type: application/json

{
  "nome": "Teste 2",
  "numeroHabilitacao": "3232332",
  "categoriaHabilitacao": "A",
  "vencimentoHabilitacao": "2023-10-20T13:39:40.335Z"
}