POST https://api-deslocamento.herokuapp.com/api/v1/Cliente
Content-Type: application/json

{
    "id": 153,
    "numeroDocumento": "123456789",
    "tipoDocumento": "RG",
    "nome": "Test 1",
    "logradouro": "Rua de Teste",
    "numero": "2213",
    "bairro": "Centro",    
    "cidade": "Curitiba",
    "uf": "SP"
}

###
GET https://api-deslocamento.herokuapp.com/api/v1/Cliente

###
DELETE https://api-deslocamento.herokuapp.com/api/v1/Cliente/247
Content-Type: application/json

{
  "id": 247
}

###
PUT https://api-deslocamento.herokuapp.com/api/v1/Cliente/247
Content-Type: application/json

{
  "id": 247,
  "nome": "Meu Ovo",
  "logradouro": "Teste",
  "numero": "Teste 3",
  "bairro": "wqeq",
  "cidade": "string",
  "uf": "string"
}