import Footer from "./components/layout/Footer";
import Navbar from "./components/layout/Navbar";
import "./globals.css";

import { ClientContextProvider } from "./context/ClientStore";

export const metadata = {
  title: "Naty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body>
        <ClientContextProvider>
          <Navbar />
          {children}
          <Footer />
        </ClientContextProvider>
      </body>
    </html>
  );
}
